language: python
python: 2.7
sudo: required
services:
  - docker
matrix:
  fast_finish: true
before_install:
- docker build -t caduvieira/plonegovbridg docker/1.1.4-debian
install:
- docker run --rm caduvieira/plonegovbridg bin/test -v -vv
script:
- true
