language: python
python: 2.7
sudo: required
services:
  - docker
matrix:
  fast_finish: true
before_script:
- docker build -t caduvieira/plonegovbridg:1.1.4-debian docker/1.1.4-debian
- docker build -t caduvieira/plonegovbridg:1.1.4-debian-test docker/1.1.4-debian-test
script:
- docker run --rm caduvieira/plonegovbridg:1.1.4-debian-test bin/test -v -vv
- cd docker/1.1.4-debian
- docker run -it --rm --privileged -v `pwd`:/root/ projectatomic/dockerfile-lint dockerfile_lint

