haproxy:
  image: eeacms/haproxy
  restart: 'always'
  ports:
  - 8080:5000
  - 1936:1936
  links:
  - idgplone
  environment:
  - BACKENDS_PORT=8080
  - SERVICE_NAMES=idgplone

idgplone:
  image: caduvieira/idgplone
  links:
  - zeoserver
  volumes_from:
  - 'plone_data'
  - 'plone_data_backup'
  environment:
  - ZEO_ADDRESS=zeoserver:8100

plone_data:
  container_name: plone_data
  image: busybox
  volumes:
  - './filestorage:/data/filestorage'
  - './blobstorage:/data/blobstorage'
  command: ['chown', '-R', '500:500', '/data']

plone_data_backup:
  container_name: plone_data_backup
  image: busybox
  volumes:
  - './backups:/data/backups'
  - './blobstoragebackups:/data/blobstoragebackups'
  command: ['chown', '-R', '500:500', '/data']

zeoserver:
  image: plone/plone:4.3.9-alpine
  command: zeoserver
